name: above-stm
channels:
  - rios
  - conda-forge
  - defaults
dependencies:
  - ipyleaflet=0.10.2=py37_0
  - ipywidgets=7.4.2=py37_0
  - qgrid=1.1.1=py37_1001
  - requests=2.21.0=py37_0
  - pandas
  - shapely